// sign in action types

export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

//sign up action types

export const SIGNUP_REQUEST = "SIGNUP_REQUEST";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAIL = "SIGNUP_FAIL";

// add new category

export const ADDCATEGORY_REQUEST = "CATEGORY_REQUEST";
export const ADDCATEGORY_SUCCESS = "CATEGORY_SUCCESS";
export const ADDCATEGORY_FAIL = "CATEGORY_FAIL";

// get all categoris

export const GETCATEGORY_REQUEST = "GETCATEGORY_REQUEST";
export const GETCATEGORY_SUCCESS = "GETCATEGORY_SUCCESS";
export const GETCATEGORY_FAIL = "GETCATEGORY_FAIL";

// add subcategory

export const ADDSUBCATEGORY_REQUEST = "ADDSUBCATEGORY_REQUEST";
export const ADDSUBCATEGORY_SUCCESS = "ADDSUBCATEGORY_SUCCESS";
export const ADDSUBCATEGORY_FAIL = "ADDSUBCATEGORY_FAIL";

// Get all subcategory

export const GET_ALLSUBCATEGORY_REQUEST = "GET_ALLSUBCATEGORY_REQUEST";
export const GET_ALLSUBCATEGORY_SUCCESS = "GET_ALLSUBCATEGORY_SUCCESS";
export const GET_ALLSUBCATEGORY_FAIL = "GET_ALLSUBCATEGORY_FAIL";

// GET subcategy

export const GETSUBCATEGORY_REQUEST = "GETSUBCATEGORY_REQUEST";
export const GETSUBCATEGORY_SUCCESS = "GETSUBCATEGORY_SUCCESS";
export const GETSUBCATEGORY_FAIL = "GETSUBCATEGORY_FAIL";

// ADD product

export const ADD_PRODUCT_REQUEST = "ADD_PRODUCT_REQUEST";
export const ADD_PRODUCT_SUCCESS = "ADD_PRODUCT_SUCCESS";
export const ADD_PRODUCT_FAIL = "ADD_PRODUCT_FAIL";

// GET Products

export const GET_ALLPRODUCTS_REQUEST = "GET_ALLPRODUCTS_REQUEST";
export const GET_ALLPRODUCT_SUCCESS = "GET_ALLPRODUCT_SUCCESS";
export const GET_ALLPRODUCT_FAIL = "GET_ALLPRODUCT_FAIL";

// GET Products with subcategory

export const GET_ALLPRODUCTS_WITH_SUBCATEGORY_REQUEST =
  "GET_ALLPRODUCTS_WITH_SUBCATEGORY_REQUEST";
export const GET_ALLPRODUCT_WITH_SUBCATEGORY_SUCCESS =
  "GET_ALLPRODUCT_WITH_SUBCATEGORY_SUCCESS";
export const GET_ALLPRODUCT_WITH_SUBCATEGORY_FAIL =
  "GET_ALLPRODUCT_WITH_SUBCATEGORY_FAIL";

// GET Single product

export const GET_PRODUCTS_REQUEST = "GET_PRODUCTS_REQUEST";
export const GET_PRODUCT_SUCCESS = "GET_PRODUCT_SUCCESS";
export const GET_PRODUCT_FAIL = "GET_PRODUCT_FAIL";

// Edit Product

export const EDIT_PRODUCTS_REQUEST = "EDIT_PRODUCTS_REQUEST";
export const EDIT_PRODUCT_SUCCESS = "EDIT_PRODUCT_SUCCESS";
export const EDIT_PRODUCT_FAIL = "EDIT_PRODUCT_FAIL";

// Add to wishList

export const ADD_WISHLIST_REQUEST = "ADD_WISHLIST_REQUEST";
export const ADD_WISHLIST_SUCCESS = "ADD_WISHLIST_SUCCESS";
export const ADD_WISHLIST_FAIL = "ADD_WISHLIST_FAIL";

// get wishlist

export const GET_WISHLIST_REQUEST = "GET_WISHLIST_REQUEST";
export const GET_WISHLIST_SUCCESS = "GET_WISHLIST_SUCCESS";
export const GET_WISHLIST_FAIL = "GET_WISHLIST_FAIL";
