// sign in action types

export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";


//sign up action types

export const SIGNUP_REQUEST = "SIGNUP_REQUEST";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAIL = "SIGNUP_FAIL";

// add new category 

export const ADDCATEGORY_REQUEST = "CATEGORY_REQUEST";
export const ADDCATEGORY_SUCCESS = "CATEGORY_SUCCESS";
export const ADDCATEGORY_FAIL = "CATEGORY_FAIL";

// get all categoris

export const GETCATEGORY_REQUEST = "GETCATEGORY_REQUEST";
export const GETCATEGORY_SUCCESS = "GETCATEGORY_SUCCESS";
export const GETCATEGORY_FAIL = "GETCATEGORY_FAIL";

// add subcategory

export const ADDSUBCATEGORY_REQUEST = "ADDSUBCATEGORY_REQUEST";
export const ADDSUBCATEGORY_SUCCESS = "ADDSUBCATEGORY_SUCCESS";
export const ADDSUBCATEGORY_FAIL = "ADDSUBCATEGORY_FAIL";

// GET subcategy

export const GETSUBCATEGORY_REQUEST = "GETSUBCATEGORY_REQUEST";
export const GETSUBCATEGORY_SUCCESS = "GETSUBCATEGORY_SUCCESS";
export const GETSUBCATEGORY_FAIL = "GETSUBCATEGORY_FAIL";